version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.6.1
    steps:
      - checkout
      - run: sh ci/setup-pkg-linux.sh
      - run: sh ci/install-llvm-linux.sh
      - run: sudo npm install -g node-gyp
      - run: npm ci
      - run: export LLVM_SUFFIX=
      - run: make -j 8
      - run: make check-stage1

workflows:
  build-test:
    jobs:
      - build
