version: 2.1

commands:
  attach_ejs_workspace:
    steps:
      - attach_workspace:
          at: /home/circleci
  persist_ejs_workspace:
    steps:
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

jobs:
  setup:
    docker:
      - image: cimg/node:20.6.1
    environment:
      LLVM_SUFFIX: ""
    steps:
      - checkout
      - run: sh ci/setup-pkg-linux.sh
      - run: sh ci/install-llvm-linux.sh
      - run: sudo npm install -g node-gyp
      - run: npm ci
      - run: make all-recurse
      - persist_ejs_workspace

  package:
    docker:
      - image: cimg/node:20.6.1
    steps:
      - attach_ejs_workspace
      - run: echo hi

  build-stage0:
    docker:
      - image: cimg/node:20.6.1
    steps:
      - attach_ejs_workspace
      - run: make stage0
      - persist_to_workspace:
          root: .
          paths:
            - ejs.exe.stage0

  check-stage0:
    docker:
      - image: cimg/node:20.6.1
    steps:
      - attach_ejs_workspace
      - run: make check-stage0

  build-stage1:
    docker:
      - image: cimg/node:20.6.1
    steps:
      - attach_ejs_workspace
      - run: make stage1
      - persist_to_workspace:
          root: .
          paths:
            - ejs.exe.stage1

  check-stage1:
    docker:
      - image: cimg/node:20.6.1
    steps:
      - attach_ejs_workspace
      - run: make check-stage1

  build-stage2:
    docker:
      - image: cimg/node:20.6.1
    steps:
      - attach_ejs_workspace
      - run: make stage2
      - persist_to_workspace:
          root: .
          paths:
            - ejs.exe.stage2

  check-stage2:
    docker:
      - image: cimg/node:20.6.1
    steps:
      - attach_ejs_workspace
      - run: make check-stage2

  build-stage3:
    docker:
      - image: cimg/node:20.6.1
    steps:
      - attach_ejs_workspace
      - run: make stage3
      - persist_to_workspace:
          root: .
          paths:
            - ejs.exe.stage3

  check-stage3:
    docker:
      - image: cimg/node:20.6.1
    steps:
      - attach_ejs_workspace
      - run: make check-stage3
      
workflows:
  build:
    jobs:
      - setup
      - build-stage0:
          requires:
            - setup
      # - check-stage0:
      #     requires:
      #       - build-stage0
      - build-stage1:
          requires:
            - build-stage0
      # - check-stage1:
      #     requires:
      #       - build-stage1
      - build-stage2:
          requires:
            - build-stage1
      # - check-stage2:
      #     requires:
      #       - build-stage2
      - build-stage3:
          requires:
            - build-stage2
      # - check-stage3:
      #     requires:
      #       - build-stage3
      # - package:
      #     requires:
      #       - check-stage0
      #       - check-stage1
      #       - check-stage2
      #       - check-stage3
