version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.6.1
    steps:
      - checkout
      - run: sudo apt update && sudo apt install clang-15 llvm-15-dev
      - run: LLVM_SUFFIX=-15 CC=clang-15 CXX=clang++-15 make
      - run: LLVM_SUFFIX=-15 CC=clang-15 CXX=clang++-15 make check-stage1

workflows:
  build-test:
    jobs:
      - build
