version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.6.1
    steps:
      - checkout
      - run: apt install clang++ llvm
      - run: make
      - run: make check-stage1

workflows:
  build-test:
    jobs:
      - build
